# Generated by Django 2.1.4 on 2019-01-15 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evento', '0013_auto_20190114_1310'),
        ('clientes', '0021_auto_20190115_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ManyToManyField(blank=True, null=True, to='clientes.Aluno')),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evento.Evento')),
            ],
        ),
    ]
