# Generated by Django 2.1.4 on 2019-01-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0013_auto_20190114_1310'),
        ('ingresso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresso',
            name='evento',
        ),
        migrations.AddField(
            model_name='ingresso',
            name='evento',
            field=models.ManyToManyField(blank=True, null=True, to='evento.Evento'),
        ),
    ]
