# Generated by Django 2.1.4 on 2019-01-15 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0025_auto_20190115_1802'),
        ('ingresso', '0004_auto_20190115_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresso',
            name='aluno',
        ),
        migrations.AddField(
            model_name='ingresso',
            name='aluno',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.Aluno'),
            preserve_default=False,
        ),
    ]
