# Generated by Django 2.1.4 on 2019-01-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0026_auto_20190115_1802'),
        ('ingresso', '0005_auto_20190115_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresso',
            name='aluno',
        ),
        migrations.AddField(
            model_name='ingresso',
            name='aluno',
            field=models.ManyToManyField(blank=True, null=True, to='clientes.Aluno'),
        ),
    ]
