# Generated by Django 2.1.4 on 2019-01-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresso', '0006_auto_20190115_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresso',
            name='caminho',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
