# Generated by Django 2.1.4 on 2019-01-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresso', '0007_ingresso_caminho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresso',
            name='caminho',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
