# Generated by Django 2.1.4 on 2019-01-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresso', '0008_auto_20190126_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresso',
            name='caminho',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
