# Generated by Django 2.1.4 on 2019-01-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresso', '0009_auto_20190126_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresso',
            name='caminho',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
