# Generated by Django 2.1.4 on 2018-12-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='token',
            field=models.CharField(default=880748, max_length=14),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='instituicao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='apelido',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='bairro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='complemento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='estado',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(null=True, upload_to='clients_photos'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='logradouro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='numero',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
