# Generated by Django 2.1.4 on 2018-12-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20181208_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='token',
            field=models.CharField(blank=True, default=681464, max_length=14, null=True),
        ),
    ]
