# Generated by Django 2.1.4 on 2018-12-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20181225_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='token',
            field=models.CharField(blank=True, default=894656, max_length=14, null=True),
        ),
    ]
