# Generated by Django 2.1.4 on 2018-12-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_auto_20181227_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='token',
            field=models.CharField(blank=True, default=220775, max_length=14, null=True),
        ),
    ]
