# Generated by Django 2.1.4 on 2019-01-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_auto_20190103_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='token',
            field=models.CharField(blank=True, default=280514, max_length=14, null=True),
        ),
    ]
