# Generated by Django 2.1.4 on 2019-01-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_auto_20190104_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='token',
            field=models.CharField(blank=True, default=378019, max_length=14, null=True),
        ),
    ]
