# Generated by Django 2.1.4 on 2019-01-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_auto_20190105_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='token',
            field=models.CharField(blank=True, default=177983, max_length=14, null=True),
        ),
    ]
