# Generated by Django 2.1.4 on 2019-01-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_auto_20190105_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='token',
            field=models.CharField(blank=True, default=148238, max_length=14, null=True),
        ),
    ]
