# Generated by Django 2.1.4 on 2019-01-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_auto_20190114_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='token',
            field=models.CharField(blank=True, default=620172, max_length=14, null=True),
        ),
    ]
