# Generated by Django 2.1.4 on 2019-01-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0026_auto_20190115_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='token',
            field=models.CharField(blank=True, default=76556, max_length=14, null=True),
        ),
    ]
