# Generated by Django 2.1.4 on 2019-01-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0028_auto_20190126_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='token',
            field=models.CharField(blank=True, default=756912, max_length=14, null=True),
        ),
    ]
