# Generated by Django 2.1.4 on 2019-01-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0029_auto_20190126_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='token',
            field=models.CharField(blank=True, default=596548, max_length=14, null=True),
        ),
    ]
