# Generated by Django 2.1.4 on 2019-01-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0048_auto_20190128_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='token',
            field=models.CharField(blank=True, default=488312, max_length=14, null=True),
        ),
    ]
