# Generated by Django 2.1.4 on 2019-01-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0049_auto_20190129_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='token',
            field=models.CharField(blank=True, default=402216, max_length=14, null=True),
        ),
    ]
