# Generated by Django 2.1.4 on 2019-03-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0050_auto_20190131_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='token',
            field=models.CharField(blank=True, default=389092, max_length=14, null=True),
        ),
    ]
