# Generated by Django 2.1.4 on 2018-12-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDaAtracao', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='eventos_photos')),
                ('cidade', models.CharField(max_length=50)),
                ('rua', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=20)),
                ('numero', models.CharField(max_length=5)),
                ('estado', models.CharField(max_length=2)),
                ('complemento', models.CharField(max_length=50)),
                ('quantidaIngresso', models.CharField(max_length=4)),
                ('promotores', models.ManyToManyField(to='promotor.PromotorEventos')),
            ],
        ),
    ]
