# Generated by Django 2.1.4 on 2019-01-04 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0008_ingresso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresso',
            name='nomeDaAtracao',
        ),
        migrations.AddField(
            model_name='ingresso',
            name='Evento',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='evento.Evento'),
            preserve_default=False,
        ),
    ]
