# Generated by Django 2.1.4 on 2019-01-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0009_auto_20190104_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingresso',
            old_name='Evento',
            new_name='evento',
        ),
    ]
