# Generated by Django 2.1.4 on 2019-01-06 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0011_auto_20190105_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresso',
            name='promotores',
        ),
    ]
