# Generated by Django 2.1.4 on 2019-01-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0013_auto_20190114_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateField(),
        ),
    ]
