# Generated by Django 2.1.4 on 2019-01-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0014_auto_20190128_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='hora_evento',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
